#+TITLE:  NuwebTCL Readme
#+AUTHOR: Mark Wroth


~Nuweb~, originally by Preston Briggs and now on [[http://sourceforge.net/projects/nuweb/][SourceForge]], is a
/literate programming/ processor that produces output code files and
TeX documentation files from a single source file, called a /web/
file. This process combines the original /tangle/ and /weave/
functions in ~WEB~ and other literate programming tools.

In its original form, ~Nuweb~ is a command line utility; the user
interacts with the program by typing the command name, various command
options, and the name of the target file.  This ~TCL/Tk~ script provides
a minimal GUI, easing the selection of the target web file, the choice of
options, and the repetitive running of ~Nuweb~.

Note that while this ~TCL/Tk~ script will /run/ without ~nuweb~,
issuing the equivalent of a command line call to ~nuweb~ without
having the separate ~nuweb~ executable is rather pointless. I've
included a Windows executable of what is by now a fairly out of date
version of ~nuweb~ in this repository. This is the version I use, as it
suits my needs, and I'd have to re-install a C compiler to update it.

I am fine with you downloading and using this code, and am interested
in suggestions for improving it. ~Nuweb~ is its own software. I
believe the compiled version included here is freely
distributable. However, interested readers should check the
[[http://sourceforge.net/projects/nuweb/][SourceForge]] page for the project for more information.  You do so at
your own risk, however; I make no guarantees about ~NuwebTCL~, ~nuweb~
itself, or the compiled version.
